package com.self.mybatis.mapper;

import com.self.mybatis.entity.ClassName;
import com.self.mybatis.entity.ClassNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    long countByExample(ClassNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    int deleteByExample(ClassNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    int deleteByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    int insert(ClassName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    int insertSelective(ClassName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    List<ClassName> selectByExample(ClassNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    ClassName selectByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    int updateByExampleSelective(@Param("record") ClassName record, @Param("example") ClassNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    int updateByExample(@Param("record") ClassName record, @Param("example") ClassNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    int updateByPrimaryKeySelective(ClassName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    int updateByPrimaryKey(ClassName record);
}