package com.self.mybatis.entity;

public class ClassName {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classname.class_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classname.class_name
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    private String className;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classname.class_id
     *
     * @return the value of classname.class_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classname.class_id
     *
     * @param classId the value for classname.class_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classname.class_name
     *
     * @return the value of classname.class_name
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classname.class_name
     *
     * @param className the value for classname.class_name
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }
}