package com.self.mybatis.entity;

public class Stu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.stu_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.stu_name
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.class_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    private Integer classId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.stu_id
     *
     * @return the value of stu.stu_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.stu_id
     *
     * @param stuId the value for stu.stu_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.stu_name
     *
     * @return the value of stu.stu_name
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.stu_name
     *
     * @param stuName the value for stu.stu_name
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.class_id
     *
     * @return the value of stu.class_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.class_id
     *
     * @param classId the value for stu.class_id
     *
     * @mbg.generated Fri Jul 15 17:28:39 CST 2022
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    @Override
    public String toString() {
        return "Stu{" +
                "stuId=" + stuId +
                ", stuName='" + stuName + '\'' +
                ", classId=" + classId +
                '}';
    }
}